name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read

jobs:   
  build:
    runs-on: ubuntu-latest

 
    steps:

    - name: Azure Login
      uses: Azure/login@v1.5.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    -  name: Azure CLI Action
       uses: Azure/cli@v1.0.9
       with:
        azcliversion: latest
        inlineScript: |
          az account list -o table

    - name: Checkout
      uses: actions/checkout@v3
          
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3.0.0
      with:
        terraform_version: "1.5.6"
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./terrafrom

    - name: Terraform Fmt
      run: terraform fmt
      working-directory: ./terrafrom

    - name: Terraform Apply & Approve
      run: terraform apply -auto-approve
      working-directory: ./terrafrom
      
